after-startup-command = ['exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 20

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = 'move-mouse window-lazy-center'

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# [[on-window-detected]]
# if.app-id = 'com.apple.systempreferences'
# if.app-name-regex-substring = 'settings'
# if.window-title-regex-substring = 'substring'
# if.workspace = 'workspace-name'
# if.during-aerospace-startup = true
# check-further-callbacks = true
# run = ['layout floating', 'move-node-to-workspace S']  # The callback itself

# [[on-window-detected]]
# if.app-name-regex-substring = 'iTerm'
# run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'NordVPN'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Bitwarden'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'qBittorrent'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'RODE UNIFY'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'OBSBOT_WebCam'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Simulator'
run = 'layout tiling'

# Move apps directly to a workspace
# Use 'aerospace list-apps' to get the app-id
# [[on-window-detected]]
# if.app-id = "com.mitchellh.ghostty"
# run = [
#   # FIX: this is a workaround for https://github.com/nikitabobko/AeroSpace/issues/68
#   # this was also observed in:
#   # - https://github.com/ghostty-org/ghostty/issues/1840
#   # - https://github.com/ghostty-org/ghostty/issues/2006
#   "layout floating",
#   "move-node-to-workspace T",
# ]

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors

# Define my fancy unicorn key notation
# [key-mapping.key-notation-to-key-code]
# unicorn = 'ä'



[gaps]
inner.horizontal = 12
inner.vertical =   12
outer.left =       12
outer.bottom =     12
outer.top =        12
outer.right =      70

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

alt-shift-f = 'fullscreen'
alt-ctrl-f = 'layout floating'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-period = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-ctrl-shift-h = 'join-with left'
alt-ctrl-shift-j = 'join-with down'
alt-ctrl-shift-k = 'join-with up'
alt-ctrl-shift-l = 'join-with right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace A'
cmd-9 = 'workspace B'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
cmd-alt-1 = 'move-node-to-workspace 1 --focus-follows-window'
cmd-alt-2 = 'move-node-to-workspace 2 --focus-follows-window'
cmd-alt-3 = 'move-node-to-workspace 3 --focus-follows-window'
cmd-alt-4 = 'move-node-to-workspace 4 --focus-follows-window'
cmd-alt-5 = 'move-node-to-workspace 5 --focus-follows-window'
cmd-alt-6 = 'move-node-to-workspace 6 --focus-follows-window'
cmd-alt-7 = 'move-node-to-workspace 7 --focus-follows-window'
cmd-alt-8 = 'move-node-to-workspace A --focus-follows-window'
cmd-alt-9 = 'move-node-to-workspace B --focus-follows-window'

cmd-alt-right = 'workspace next'
cmd-alt-left = 'workspace prev'

alt-q = 'workspace-back-and-forth'
alt-shift-q = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-s = 'mode service'
alt-shift-a = 'mode apps'

alt-t = 'exec-and-forget open -a /Applications/Ghostty.app -n'
alt-a = 'exec-and-forget open -a /Applications/Arc.app'
alt-o = 'exec-and-forget open -a /Applications/Obsidian.app'
alt-c = 'exec-and-forget open -a /Applications/Chrome.app'
alt-v = 'exec-and-forget open -a "/Applications/Visual Studio Code - Insiders.app"'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

[mode.apps.binding]
alt-w = ['exec-and-forget open -a /Applications/Ghostty.app', 'mode main']
esc = ['reload-config', 'mode main']